routes/web.php
<?php

use App\Http\Controllers\Admin\Item\ItemController as AdminItemController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Player\Cart\CartController as PlayerCartController;
use App\Http\Controllers\Player\Item\ItemController as PlayerItemController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');

//--Admin---------------------------------------------------------------------------------------------------------------
Route::prefix('/admin/items')->middleware(['auth', 'role:admin'])->name('admin.items.')->group(function () {
    Route::get('/', [AdminItemController::class, 'index'])->name('index');
    Route::get('/add', [AdminItemController::class, 'add'])->name('add');
    Route::get('/list', [AdminItemController::class, 'list'])->name('list');
});

//--Player--------------------------------------------------------------------------------------------------------------
Route::prefix('/player')->middleware(['auth', 'role:player'])->name('player.')->group(function () {
    Route::get('/shopping-cart/', [PlayerCartController::class, 'index'])->name('shopping-cart.index');
    Route::prefix('/items')->name('items.')->group(function () {
        Route::get('/', [PlayerItemController::class, 'index'])->name('index');
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Minecraft') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">

        @include('layouts.navigation')

        <main class="py-4 ">
            <div class="container">
                <div class="p-3 mb-1 bg-white border border-1 rounded-3 shadow-sm sm:rounded-lg">
                    @yield('content')
                </div>
            </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            Main page
        </a>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="nav nav-pills me-auto ms-4">

                <!-- Player Links -->
                @can('player')
                    <a href="{{ route('player.items.index') }}" class="nav-link ms-2 {{ request()->routeIs('player.items.*') ? 'active' : '' }}">
                        Items
                    </a>
                @endcan

                <!-- Admin Links -->
                @can('admin')
                    <a href="{{ route('admin.items.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.items.*') ? 'active' : '' }}">
                        Admin Items
                    </a>
                @endcan
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">

                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item mt-1 me-4">
                        @can('player')
                            <cart-counter-component ref="cartCounter" cart-route="{{ route('player.shopping-cart.index') }}"
                                                    user-id="{{ auth()->user()->id }}"></cart-counter-component>
                        @endcan

                    </li>

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest

            </ul>
        </div>
    </div>
</nav>